//react
export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

//app
export const LOADING_ON = 'LOADING_ON';
export const LOADING_OFF = 'LOADING_OFF';

export const RESET_STATE = "RESET_STATE";

export const ERROR = 'ERROR';
export const TAB_CHANGED = 'TAB_CHANGED';

export const FACEBOOK_LOGGED_IN = 'FACEBOOK_LOGGED_IN';
export const BACKEND_LOGIN = 'BACKEND_LOGIN';
export const BACKEND_LOGIN_REQUESTED = 'BACKEND_LOGIN_REQUESTED';
export const BACKEND_LOGIN_DONE = 'BACKEND_LOGIN_DONE';
export const BACKEND_LOGIN_FAILED = 'BACKEND_LOGIN_FAILED';


//fileList
export const FETCH_FILE_LIST_REQUESTED = 'FETCH_FILE_LIST_REQUESTED';
export const FETCH_FILE_LIST_DONE = 'FETCH_FILE_LIST_DONE';
export const FETCH_FILE_LIST_FAILED = 'FETCH_FILE_LIST_FAILED';
export const CLEAR_FILE_LIST = 'CLEAR_FILE_LIST';

//enable ui file edit
export const FILE_EDIT = 'FILE_EDIT';
//file edit api call
export const FILE_EDIT_APPROVED_REQUESTED = 'FILE_EDIT_APPROVED_REQUESTED';
export const FILE_EDIT_APPROVED_DONE = 'FILE_EDIT_APPROVED_DONE';
export const FILE_EDIT_APPROVED_FAILED = 'FILE_EDIT_APPROVED_FAILED';

export const CREATE_DOCUMENT_REQUESTED = 'CREATE_DOCUMENT_REQUESTED';
export const CREATE_DOCUMENT_DONE = 'CREATE_DOCUMENT_DONE';
export const CREATE_DOCUMENT_FAILED = 'CREATE_DOCUMENT_FAILED';

export const UPLOAD_FILE_REQUESTED = 'UPLOAD_FILE_REQUESTED';
export const UPLOAD_FILE_DONE = 'UPLOAD_FILE_DONE';
export const UPLOAD_FILE_FAILED = 'UPLOAD_FILE_FAILED';

export const SEARCH_FILE = 'SEARCH_FILE';

export const MARK_FILE_REQUESTED = 'MARK_FILE_REQUESTED';
export const MARK_FILE_DONE = 'MARK_FILE_DONE';
export const MARK_FILE_FAILED = 'MARK_FILE_FAILED';


//myStudiesList
export const FETCH_MY_GROUPS_LIST_REQUESTED = 'FETCH_MY_GROUPS_LIST_REQUESTED';
export const FETCH_MY_GROUPS_LIST_DONE = 'FETCH_MY_GROUPS_LIST_DONE';
export const FETCH_MY_GROUPS_LIST_FAILED = 'FETCH_MY_GROUPS_LIST_FAILED';

export const GROUP_ITEM_SELECTED = 'GROUP_ITEM_SELECTED';
export const SUBJECT_ITEM_SELECTED = 'SUBJECT_ITEM_SELECTED';

//createGroupPage
export const FETCH_ACADEMIES_REQUESTED = 'FETCH_ACADEMIES_REQUESTED';
export const FETCH_ACADEMIES_DONE = 'FETCH_ACADEMIES_DONE';
export const FETCH_ACADEMIES_FAILED = 'FETCH_ACADEMIES_FAILED';

export const FETCH_DEGREES_REQUESTED = 'FETCH_DEGREES_REQUESTED';
export const FETCH_DEGREES_DONE = 'FETCH_DEGREES_DONE';
export const FETCH_DEGREES_FAILED = 'FETCH_DEGREES_FAILED';

export const CREATE_GROUP_ACADEMY_SELECTED = 'CREATE_GROUP_ACADEMY_SELECTED';
export const CREATE_GROUP_DEGREE_SELECTED = 'CREATE_GROUP_DEGREE_SELECTED';

export const CREATE_GROUP_REQUESTED = 'CREATE_GROUP_REQUESTED';
export const CREATE_GROUP_DONE = 'CREATE_GROUP_DONE';
export const CREATE_GROUP_FAILED = 'CREATE_GROUP_FAILED';

export const CREATE_GROUP_DATA_CHANGED = 'CREATE_GROUP_DATA_CHANGED';
export const CLEAR_GROUP_CREATION_DATA = 'CLEAR_GROUP_CREATION_DATA';


//myGroupsPage
export const FETCH_MY_GROUPS_REQUESTED = 'FETCH_MY_GROUPS_REQUESTED';
export const FETCH_MY_GROUPS_DONE = 'FETCH_MY_GROUPS_DONE';
export const FETCH_MY_GROUPS_FAILED = 'FETCH_MY_GROUPS_FAILED';

//groupRecruitment
export const ENTER_TO_GROUP_REQUESTED = 'ENTER_TO_GROUP_REQUESTED';
export const ENTER_TO_GROUP_DONE = 'ENTER_TO_GROUP_DONE';
export const ENTER_TO_GROUP_FAILED = 'ENTER_TO_GROUP_FAILED';
export const ENTER_TO_GROUP_CLEAR = 'ENTER_TO_GROUP_CLEAR';

//Explore subjects list
export const FETCH_SUBJECTS_REQUESTED = 'FETCH_SUBJECTS_REQUESTED';
export const FETCH_SUBJECTS_DONE = 'FETCH_SUBJECTS_DONE';
export const FETCH_SUBJECTS_FAILED = 'FETCH_SUBJECTS_FAILED';

export const FETCH_FILES_REQUESTED = 'FETCH_FILES_REQUESTED';
export const FETCH_FILES_DONE = 'FETCH_FILES_DONE';
export const FETCH_FILES_FAILED = 'FETCH_FILES_FAILED';

export const FETCH_SUBJECT_DETAILS_REQUESTED = 'FETCH_SUBJECTS_DETAILS_REQUESTED';
export const FETCH_SUBJECT_DETAILS_DONE = 'FETCH_SUBJECTS_DETAILS_DONE';
export const FETCH_SUBJECT_DETAILS_FAILED = 'FETCH_SUBJECTS_DETAILS_FAILED';

export const SUBJECT_SELECTED = 'SUBJECT_SELECTED';

export const FETCH_SUBJECT_COMMENTS_REQUESTED = 'FETCH_SUBJECT_COMMENTS_REQUESTED';
export const FETCH_SUBJECT_COMMENTS_DONE = 'FETCH_SUBJECT_COMMENTS_DONE';
export const FETCH_SUBJECT_COMMENTS_FAILED = 'FETCH_SUBJECT_COMMENTS_FAILED';

export const ADD_COMMENT_REQUESTED = 'ADD_COMMENT_REQUESTED';
export const ADD_COMMENT_DONE = 'ADD_COMMENT_DONE';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';

export const FETCH_PUBLIC_FILE_LIST_REQUESTED = 'FETCH_PUBLIC_FILE_LIST_REQUESTED';
export const FETCH_PUBLIC_FILE_LIST_DONE = 'FETCH_PUBLIC_FILE_LIST_DONE';
export const FETCH_PUBLIC_FILE_LIST_FAILED = 'FETCH_PUBLIC_FILE_LIST_FAILED';

export const MARK_SUBJECT_REQUESTED = 'MARK_FILE_REQUESTED';
export const MARK_SUBJECT_DONE = 'MARK_FILE_DONE';
export const MARK_SUBJECT_FAILED = 'MARK_FILE_FAILED';

export const CURRENT_SEARCHING_CHANGE = 'CURRENT_SEARCHING_CHANGE';






