export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

//fileList
export const FETCH_FILE_LIST = 'FETCH_FILE_LIST';
export const FETCH_FILE_LIST_REQUESTED = 'FETCH_FILE_LIST_REQUESTED';
export const FETCH_FILE_LIST_DONE = 'FETCH_FILE_LIST_DONE';
export const FETCH_FILE_LIST_FAILED = 'FETCH_FILE_LIST_FAILED';
