//react
export const LOCATION_CHANGE='@@router/LOCATION_CHANGE';

//app
export const TAB_CHANGED='TAB_CHANGED';

//fileList
export const FETCH_FILE_LIST = 'FETCH_FILE_LIST';
export const FETCH_FILE_LIST_REQUESTED = 'FETCH_FILE_LIST_REQUESTED';
export const FETCH_FILE_LIST_DONE = 'FETCH_FILE_LIST_DONE';
export const FETCH_FILE_LIST_FAILED = 'FETCH_FILE_LIST_FAILED';
export const CLEAR_FILE_LIST = 'CLEAR_FILE_LIST';

//myStudiesList
export const FETCH_MY_STUDIES_LIST = 'FETCH_MY_STUDIES_LIST';
export const FETCH_MY_STUDIES_LIST_REQUESTED = 'FETCH_MY_STUDIES_LIST_REQUESTED';
export const FETCH_MY_STUDIES_LIST_DONE = 'FETCH_MY_STUDIES_LIST_DONE';
export const FETCH_MY_STUDIES_LIST_FAILED = 'FETCH_MY_STUDIES_LIST_FAILED';

export const ACADEMY_ITEM_SELECTED = 'ACADEMY_ITEM_SELECTED';
export const SEMESTER_ITEM_SELECTED = 'SEMESTER_ITEM_SELECTED';
export const SUBJECT_ITEM_SELECTED = 'SUBJECT_ITEM_SELECTED';



